name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm build
      run: |
          npm install
          npm run build --if-present
    - name: Archive compiled js
      uses: actions/upload-artifact@v3
      with:
        name: compiled-js
        path: |
          out
    
   image:

    runs-on: ubuntu-latest

    steps:
    - name: Download compiled js
      uses: actions/download-artifact@v3
      with:
        name: compiled-js
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ivona:$(date +%s)
